### ISSUE TITLE
Would it work with Focus AXR-SD

### ISSUE THREAD

**Issue by badabing2005** [klaasnicolaas/home-assistant-glow#1]
Hi,

Thanks for this great code / device
Would it work with Focus AXR-SD ?
![image](https://user-images.githubusercontent.com/22603312/128221072-edb4627b-0bea-4627-ad7c-2db2b79309f1.png)

Thanks

**Comment by fnordpojk** [comment]
It has an optical port, but it appears to be only for configuration, not for metering.

**Comment by badabing2005** [comment]
Thanks, and sorry to hear that I can't make use of it.
