### ISSUE TITLE
No LED flash

### ISSUE THREAD

**Issue by cpoulsen** [klaasnicolaas/home-assistant-glow#103]
Hi

Using an ESP8266 wired as described i get no flashes from the LED. Tried with two different LEDs

**Comment by klaasnicolaas** [comment]
Do you mean status led? Do you use a cathode or anode variant?

**Comment by cpoulsen** [comment]
Yes the status led. Using catode

**Comment by peterczarlarsen** [comment]
has the same issue and hardware, @cpoulsen did we make some mistake or did you just ignore it?

**Comment by cpoulsen** [comment]
@peterczarlarsen i chose to ignore it :)
