### ISSUE TITLE
Sensor for current

### ISSUE THREAD

**Issue by robinelfving** [klaasnicolaas/home-assistant-glow#113]
Would it be possible to implement sensor to show the current Amps aswell as the watts?

**Comment by klaasnicolaas** [comment]
From what exactly? the ESP?

**Comment by robinelfving** [comment]
Sorry, i know it cannot be a messarued value. But I want it as än calculated value based on the Watt reading. My coding isnt good enough. 

I = P * V
I = Amp 
P = Watt
V = Volt

Would that be possible?

**Comment by klaasnicolaas** [comment]
I think this is quite out of scope. It would be better to tackle this with CT clamps and then have the formulas calculated with template sensors in Home Assistant.

**Comment by robinelfving** [comment]
Ok, thank you for the reply!

**Comment by robinelfving** [comment]
Just for information.

I did solve this like this:
>   - platform: template
    name: "${friendly_name} - Amps"
    id: sensor_total_amps
    unit_of_measurement: 'A'
    icon: mdi:current-ac
    accuracy_decimals: 1
    lambda: |-
      return id(sensor_energy_pulse_meter).state / 230;
    update_interval: 1s
