### ISSUE TITLE
Not compiling

### ISSUE THREAD

**Issue by nzneil22** [klaasnicolaas/home-assistant-glow#114]
Hello, i am trying to install the home assistant glow binary using esphome on my HA instance. 

I keep getting thee following error:

![image](https://user-images.githubusercontent.com/88832123/148788721-9c1e393c-e7c4-499e-9b3d-bfa3adb4002e.png)

Any insights? I am new to this 

Neil

**Comment by klaasnicolaas** [comment]
Which ESPHome version are you using? I don't experience any problems compiling the binary myself 🤔

**Comment by nzneil22** [comment]
I am using version 2021.12.3

**Comment by nzneil22** [comment]
Thanks for your suggestion, yet I have already tried. It has not worked either. 

I am running Home Assistant OS on an RPI 4.

**Comment by nzneil22** [comment]
I'm sorry what YAML config? 

I created an esphome file where I have the following code:
https://controlc.com/5b4452ca

**Comment by klaasnicolaas** [comment]
I found some threads, what could be interesting:
- https://github.com/esphome/issues/issues/1386
- https://community.home-assistant.io/t/lower-the-number-of-cc1plus-compilation-threads/238911/8

On what kind of device are you running Home Assistant?

**Comment by nzneil22** [comment]
I will look into them thanks.

I am running a Home Assistant OS instance on a Raspberry Pi 4.

- Neil

**Comment by nzneil22** [comment]
Hello @klaasnicolaas 

For some reason, I compiled the YAML file on a completely fresh install of home assistant os and it worked without any flaws.

I guess my esphome install was corrupt. 

Thank you for your help.

Neil
