### ISSUE TITLE
S0 output

### ISSUE THREAD

**Issue by zorrosweden** [klaasnicolaas/home-assistant-glow#126]
Is it possible to use the S0 output on the electricity meter instead of the photodiode card

**Comment by msteve72** [comment]
I'm also interested, I have a meter like this

[(https://ema-elektro.sk/UserFiles/Image/Schema%20zapojenia%20elektromer%20LE-02D%20MID.jpg)]
[https://images-cbelektro-cdn.rshop.sk/prod-main/products/9f5e10f95960e3ea6d65cc37e8afb771.jpg]

**Comment by klaasnicolaas** [comment]
In theory it could be, but it won't be plug and play. An alternative would be: https://github.com/huizeBruin/s0tool, but he currently only sells his boards in the Netherlands.
