### ISSUE TITLE
consumption data is not saved after reboot

### ISSUE THREAD

**Issue by Dilkins85** [klaasnicolaas/home-assistant-glow#13]
after reboot, all readings are reset to zero, is this normal? and for some reason, the new integration of energy does not see the readings (. is it so for everyone?

**Comment by klaasnicolaas** [comment]
It is normal for the values to reset after rebooting or flashing, if you would like to keep the values, you could use [utility_meter](https://www.home-assistant.io/integrations/utility_meter/). But this behavior is not a problem for the energy dashboard calculatings.

If you don't have any readings in the dashboard, check if the entity is included in your recorder.

**Comment by jacauc** [comment]
Very new to esphome, would you mind giving me some more pointers on how to substitute utility meter into the code?

**Comment by klaasnicolaas** [comment]
I don't really understand your question, this is not code that you put in esphome but an integration that you use in Home Assistant.

**Comment by jacauc** [comment]
Oh! Thank you!

**Comment by klaasnicolaas** [comment]
Has your problem already been solved? Otherwise I would like to close this issue.
