### ISSUE TITLE
LDR - any way to make it work?

### ISSUE THREAD

**Issue by QGgWW2WhH** [klaasnicolaas/home-assistant-glow#14]
I know you have written that LDRs won't work - any reason why?

**Comment by klaasnicolaas** [comment]
Because an LDR has a higher chance of false readings, but there are some people who use an LDR (with extra config options in their YAML file, check the issues for more info).

So they do work, but I don't recommend using them.

**Comment by jacauc** [comment]
This did it for me.
https://github.com/klaasnicolaas/home-assistant-glow/issues/10#issuecomment-894485575

**Comment by klaasnicolaas** [comment]
In that case, I will close this issue.
