### ISSUE TITLE
Specification for photodiode

### ISSUE THREAD

**Issue by newhinton** [klaasnicolaas/home-assistant-glow#152]
The current information about the required a photodiode is insufficient. Could you please add a proper part/specification for it?

I assume it is a normal photodiode with the appropriate controllerboard, but the provided links are neither trustworthy nor a reliable source for information about the parts. (Both links redirect through tc.tradetracker.net)

Is the imp/kwh-led a "normal" one or an ir one? Datasheets for the powermeter indicate its an ir-led, will a normal sensor still work?

**Comment by klaasnicolaas** [comment]
You are free to add the missing information via a pull request, it is unclear to me which information you are missing.

> I assume it is a normal photodiode with the appropriate controllerboard, but the provided links are neither trustworthy nor a reliable source for information about the parts. (Both links redirect through tc.tradetracker.net)

It is indeed a photodiode connected to a controller board. The Home Assistant Glow is made to detect a normal LED flash, I personally have no experience with using it in combination with an IR LED.
