### ISSUE TITLE
Weird peak showing in HA

### ISSUE THREAD

**Issue by thecivvie** [klaasnicolaas/home-assistant-glow#154]
![Screenshot 2022-03-31 124508](https://user-images.githubusercontent.com/34013299/161047823-7bb4f22b-c565-465c-9094-5990f727a0a7.png)
I am getting the odd peak over 200,000 w which distrots the graphs. What would be causing such high peaks. Usually happens during the night time when I am asleep but sometimes during the day

**Comment by klaasnicolaas** [comment]
There could be several reasons why this could go wrong. Suspect that 1 pulse was measured as 2 separate pulses, possible solution could be by setting an `internal_filter`.

**Comment by thecivvie** [comment]
ok will have to check and see

**Comment by thecivvie** [comment]
Thanks, that sorted it for me
