### ISSUE TITLE
Minimal case

### ISSUE THREAD

**Issue by smulle48** [klaasnicolaas/home-assistant-glow#156]
First of all, an amazing project :-)

I thought I would share my minimal case for this project.

As the diode on my meter was just next to the display, I could not use the original case, as it blocked part of the display.

The case for the d1 mini have room for pinheader, and as the sensor case, secures the wires/usb cable so you don't accidentially pull them out.

Both cases are secured with double sided carpet tape and hold perfectly.

https://www.thingiverse.com/thing:5347120

**Comment by klaasnicolaas** [comment]
Do you have some pictures of how it was finally installed on your meter? (possibly adding images to thingiverse)

**Comment by smulle48** [comment]
> Do you have some pictures of how it was finally installed on your meter? (possibly adding images to thingiverse)

Sure. Here are some :-)
![image](https://user-images.githubusercontent.com/24297824/165560490-55052cc9-782e-404d-93cf-c864c9815689.jpeg)
![image](https://user-images.githubusercontent.com/24297824/165560547-25dd36f3-5dc6-4e2f-bb54-c036874786f7.jpeg)
![image](https://user-images.githubusercontent.com/24297824/165560611-c85e6f20-ec40-41dd-bc0f-261d62045814.jpeg)
![image](https://user-images.githubusercontent.com/24297824/165560702-5b83662a-e924-4d5c-9d48-d6d1c216d31a.jpeg)
