### ISSUE TITLE
GPIO12 causes ESP boot issue

### ISSUE THREAD

**Issue by clough360** [klaasnicolaas/home-assistant-glow#164]
Using GPIO12 for the sensing LED interferes with the boot process as it is a strapping pin. 
The compilation process also warns about this:
![image](https://user-images.githubusercontent.com/12503052/164966424-7e9413ae-6bd2-4458-ada4-bd94fd9c1435.png)

This caused an issue for me where the device would boot only intermittently with GPIO12 connected. When I switched to GPIO13, the issue device booted (and worked) correctly.

I suggest changing the default yaml config file and related documentation to use GPIO13

**Comment by klaasnicolaas** [comment]
Seems like a good plan, I have no idea whether GPIO13 is better, but that something needs to be changed, that's one thing for sure.

**Comment by smarquard** [comment]
For me GPIO12 caused the OTA update to fail. I switched to GPIO5 which resolved the issue. It would be good to change the default to something else.

**Comment by anoadragon453** [comment]
FYI `GPIO15` was also a strapping pin on my board. `GPIO16` was not, however.
