### ISSUE TITLE
Spikes every 2hrs

### ISSUE THREAD

**Issue by DSew20** [klaasnicolaas/home-assistant-glow#179]
Hello,

This is a great app and great use of ESPhome.  I have had this running for a few months, and there was always a small periodic spike that I put down to a freezer condenser turning on or something similar.

However, with the recent (very) warm weather, the tape holding the GLOW sensor to the meter flashing LED became unstuck.  So, for a few days the sensor was not picking up any power "flashes".  But, upon inspection I am still seeing the periodic spikes making me wonder if this caused by hardware / firmware / software.

Below is a screenshot.  You can see the readings go from zero for two hours, then a spike, then again, etc.

Any throughs?
  
![image](https://user-images.githubusercontent.com/77920790/178775148-7f237b01-8ee0-4e2c-9471-39337dc9832b.png)

**Comment by DSew20** [comment]
My latest thinking is could it be the smart electricity meter introducing the spike.  Perhaps when it is sending the electricity usage via WAN to the electricity supplier?  We have a Liberty 100 Smart (rather basic) meter, which uses GPRS to communicate with the supplier.  Could this introduce a spikes as above every 2 hours or so?

**Comment by IliasEagle** [comment]
It is noise coming from some device near by. In my case it is the gas boiler.
