### ISSUE TITLE
Esp8266 module

### ISSUE THREAD

**Issue by phillipmj** [klaasnicolaas/home-assistant-glow#2]
Hi,

Are it possible to port this great project to esp8266 chip type ?

best regards
Phillip J.

**Comment by klaasnicolaas** [comment]
With some small changes in the yaml code, it will work 😉

**Comment by phillipmj** [comment]
Nice :) Need to dig down how to do it :3

**Comment by klaasnicolaas** [comment]
Well change this:
- platform
- board

And possibly that you use other pins, then you can adjust those as well. But I would advise to use a ESP32 😄

**Comment by cheesyger** [comment]
works like a charme with esp8266
