### ISSUE TITLE
Case files

### ISSUE THREAD

**Issue by pettib** [klaasnicolaas/home-assistant-glow#207]
Hi
Is it possible to get the .step files for the case ?
Newer versions of the ESP-32 has the wifi antenna outside the board so the case is to short.
With the .step files we can make an larger version.

**Comment by klaasnicolaas** [comment]
Can you specify which ESP32 it is?

**Comment by pettib** [comment]
![esp-32](https://user-images.githubusercontent.com/6399803/195510463-431b4f5d-2a51-4eb3-8723-939f60fa810b.jpg)

**Comment by klaasnicolaas** [comment]
PR opened in which you can find the step file.
