### ISSUE TITLE
Constantly rebooting on a 10 minute cycle.

### ISSUE THREAD

**Issue by maverikgrass** [klaasnicolaas/home-assistant-glow#21]
The sensor, for the most part works great. But after 9-11 minutes of running it shuts off for exactly 10 minutes. Could it be a temperature issue or? (It's really quite cold tonight) Also this is my first night trying the sensor for real.

**Comment by LarsNorgaard** [comment]
You could try unplugging the sensors and see how the esp acts.

**Comment by klaasnicolaas** [comment]
I haven't experienced this problem yet, is there anything to get out of the logs? Which board do you use and does it get enough power?

**Comment by maverikgrass** [comment]
Somehow the solution was to change.
ota:
  safe_mode: true
  reboot_timeout: 10min
  num_attempts: 5
To
ota:
  safe_mode: true
  reboot_timeout: 5min
  num_attempts: 5
Now it's been running fine for hours.
