### ISSUE TITLE
Which sensor to use in Energy dashboard

### ISSUE THREAD

**Issue by mtb-xt** [klaasnicolaas/home-assistant-glow#212]
Hi everyone, thanks for this awesome project!

I don't understand one thing, though - the config exposes two values - daily energy and total energy. Which one do I use in HASS Energy dashboard?

**Comment by cieska** [comment]
Hi,
Depends what you want to archive. A quick answer is use total. Try in few times and you will find out.

**Comment by klaasnicolaas** [comment]
It doesn't matter which one you use, in the end long term statistics treat it the same way. Personally I use the total entity

**Comment by mtb-xt** [comment]
Thank you
