### ISSUE TITLE
Can´t install with ESPHome

### ISSUE THREAD

**Issue by pettib** [klaasnicolaas/home-assistant-glow#214]
Tried to do as the documentation show.
I downloaded the yaml file in to ESPHome and edit the wifi settings but always get the error message: Error fetching configuration information.

Any Ide what to look at ?

I have done this before with an older version and that one is still working.

**Comment by klaasnicolaas** [comment]
> Error fetching configuration information.

When do you get this message?

**Comment by klaasnicolaas** [comment]
You could check if you have set the correct board type, since you probably don't use ESP32S. It could also very well be that this ESP32 is not yet supported.

**Comment by phantom8** [comment]
how do i check which board type this esp32 CH9102x has? I'm able to install the generic frimware from ESP web tools and connect to the web interface with no issues.

**Comment by klaasnicolaas** [comment]
But then you apparently have an esp8266 and not an esp32? 😅
