### ISSUE TITLE
Photodiode alternatives

### ISSUE THREAD

**Issue by siccovansas** [klaasnicolaas/home-assistant-glow#23]
The linked photodiode is (temporary) out of stock: https://banggood.app.link/2OqdFiWIgib
I can't find it on other webshops (others are also out of stock). Does anyone know where to get it or are there alternatives?

**Comment by jessexoc** [comment]
AliExpress (usually takes longer to deliver than BangGood though): https://www.aliexpress.com/item/1005001640685908.html ?

**Comment by siccovansas** [comment]
Thanks! @klaasnicolaas is it a good idea to add this alternative to the README?

**Comment by Fossdal** [comment]
i use a TLS257 Light to Voltage sensor
https://www.aliexpress.com/item/32666821607.html?spm=a2g0o.productlist.0.0.b6c4428fsmBb6f&algo_pvid=d573981f-ca42-4bfb-a096-a75be9555436&algo_exp_id=d573981f-ca42-4bfb-a096-a75be9555436-8&pdp_ext_f=%7B%22sku_id%22%3A%2260025438761%22%7D

**Comment by klaasnicolaas** [comment]
The link to aliexpress is now in the docs 😉

**Comment by simonbuerger** [comment]
@Fossdal sorry for the n00b question here, but if I were to get something like that instead (much cheaper and more readily available where I am) - what would the A0, DO, VCC, GND correspond to from the photodiode connection table?

**Comment by Fossdal** [comment]
@simonbuerger  this is how i have connected it
![image](https://user-images.githubusercontent.com/15619646/144471536-921d97cd-125c-452f-ae9e-d4e27ca2cb81.png)

**Comment by simonbuerger** [comment]
@Fossdal thank you!!! Does that impact the rest of the configuration in any way? Also have you found it to be accurate?

**Comment by Fossdal** [comment]
@simonbuerger  my bill says 155 kWh for November and home assistant says 156.6 kWh. so yes it is accurate.
no impact on configuration

**Comment by simonbuerger** [comment]
@Fossdal thanks for the help. Last question I promise - what size capacitor did you use? (apologies I really am new at this, more of a software guy 😬)

**Comment by Fossdal** [comment]
i just grabbed some random small one i got laying around. it is  470 pF

**Comment by simonbuerger** [comment]
@Fossdal I just wanted to stop by and thank you for all your help above! I have this set up for the last month or so with the light to voltage converter and it's working perfectly.
