### ISSUE TITLE
3200 / kwh meter - esphome config ?

### ISSUE THREAD

**Issue by richardholst** [klaasnicolaas/home-assistant-glow#24]
Hi there,

I have a meter that has a 3200 / kwh pulse rate rather than a 1000 /kwh pulse rate ..how would I change the config to allow for this ..I have tried to work it out but have not found anything that makes sense 

if you could let me know where and how I need to change my config that woul be amazing

cheers

Richard

**Comment by klaasnicolaas** [comment]
Try version 1.2.0, we have improved the way of configuring the **imp/kWh** pulse rate. From now on you fill this value at the top under substitutions 😉
