### ISSUE TITLE
Energy jump at the start of the day since 21/10/22

### ISSUE THREAD

**Issue by RATA1** [klaasnicolaas/home-assistant-glow#246]
I have had glow running for several months and was working perfectly. Recently I noticed that the energy was incorrect and saw these values in HA;

![image](https://user-images.githubusercontent.com/27967108/208716299-6c71878f-46dd-4f67-8625-d9b97ac46404.png)

Looking back in the history I see that it started to happen overnight on 21/10. Seems I was getting updates of zero regularly but then it stopped and every morning since it jumps from zero to a few hundred Watt hours instantly which then skews the figures.

![image](https://user-images.githubusercontent.com/27967108/208716760-6a93f75a-6177-42a4-9e0d-2da6c63cac63.png)

Not sure if something in HA broke it or an ESP update.
Anyone else seen this or can shed some light on it?

I have set `internal_filter: 100ms` but this has made no difference.

Thanks

**Comment by klaasnicolaas** [comment]
Strange, I've never come across that before

**Comment by RATA1** [comment]
Yes, very odd. That is how mine used to look.

Today on looking at the power I get two blips when there was no generation. I use this only for a solar generation meter (as the inverter's energy over-reads) and it was dark at these times.

I have overlaid the inverter's power and it has no spikes but other than that it tracks almost identically.
![image](https://user-images.githubusercontent.com/27967108/208728176-31c7e4cd-d0bc-4601-9d77-2ca9be7fc738.png)
