### ISSUE TITLE
Daily Energy Numbers

### ISSUE THREAD

**Issue by crcerdas** [klaasnicolaas/home-assistant-glow#256]
Guys,

Could you help me if the House Daily Energy numbers are OK?. House power consumption looks good.

![image](https://user-images.githubusercontent.com/35315633/211197811-ca278c5d-35c1-41f2-9856-44b8dff64930.png)

Thnks

**Comment by klaasnicolaas** [comment]
The day entity is not correct, it seems way too much compared to your total entity. Could it be that too much was measured in the beginning when adjusting the photodiode?

**Comment by crcerdas** [comment]
> The day entity is not correct, it seems way too much compared to your total entity. Could it be that too much was measured in the beginning when adjusting the photodiode?

Probably, i will check tomorrow again.

**Comment by crcerdas** [comment]
> The day entity is not correct, it seems way too much compared to your total entity. Could it be that too much was measured in the beginning when adjusting the photodiode?

All seem come back to normal numbers, probably was when adjusting the Photodiode. Thnks for the Work!
