### ISSUE TITLE
Pulse Rate

### ISSUE THREAD

**Issue by Danifly80** [klaasnicolaas/home-assistant-glow#259]
Hi,
I've some problem in configure my pulse rate that in my house (in France) meter is 1Wh/imp
which value should I use in the yalm file?

Thanks

**Comment by klaasnicolaas** [comment]
This question has come up before in the discussions: https://github.com/klaasnicolaas/home-assistant-glow/discussions/239

**Comment by Danifly80** [comment]
> This question has come up before in the discussions: #239

Thanks and sorry for didn't see it before
