### ISSUE TITLE
Flashing to esp

### ISSUE THREAD

**Issue by Craitz1** [klaasnicolaas/home-assistant-glow#260]
I tried to use your web flasher tool to flash to a esp device. I tried a 8266 and a d1 mini and a esp32 and they all come back unsupported via the web browser. Can you fix this because even with the 2 different 8266 small and large it does the same. I do have the proper hardware just ur tool says no.

**Comment by klaasnicolaas** [comment]
ESPHome web tools assumes that you use an ESP32, in the future I want to improve that. If you use a different board type, you have to work with the yaml file yourself.
