### ISSUE TITLE
Reset data in Energy Dashboard

### ISSUE THREAD

**Issue by DrJon85** [klaasnicolaas/home-assistant-glow#263]
Hi i have recently reinstalled on a new esp32. when setting up initially i have somehow managed to 'use' -117,951.32 kWh.
how do i reset this to 0 please?!

**Comment by klaasnicolaas** [comment]
I also asked you for some more information 😉 
Because I don't know exactly what you mean yet, are you talking about one of the entities or a value in the energy dashboard etc.

**Comment by DrJon85** [comment]
Hi, yes it is the value in the energy dashboard that has been picked up.
![image](https://user-images.githubusercontent.com/57183034/212515712-5ff0de23-a9b9-40c2-82ef-c216e4a41caf.png)

**Comment by klaasnicolaas** [comment]
You can change this in `developer tools` -> `statistics`. On this page, Home Assistant lets you know if there are problems with your statistics and you can correct the value for a specific entity if necessary.

[![Open your Home Assistant instance and show your statistics developer tools.](https://my.home-assistant.io/badges/developer_statistics.svg)](https://my.home-assistant.io/redirect/developer_statistics/)

**Comment by DrJon85** [comment]
thankyou, is there a way to delete all data and start fresh?
