### ISSUE TITLE
Calibrate total consumption

### ISSUE THREAD

**Issue by naofireblade** [klaasnicolaas/home-assistant-glow#264]
I‘d like to have a way to calibrate the total consumption sensor value. So that the total on glow is the same total as on the real energy meter.

**Comment by klaasnicolaas** [comment]
I think this is a duplicate of: https://github.com/klaasnicolaas/home-assistant-glow/discussions/190

**Comment by naofireblade** [comment]
Correct, sorry. Will try to provide a PR.
