### ISSUE TITLE
Raspberry Pi 3B - error 1 

### ISSUE THREAD

**Issue by hausmannl** [klaasnicolaas/home-assistant-glow#267]
Hi everyone, I have a question. I'm trying to upload SW to an ESP32 and when I compile it gives me the following:

Linking /data/home-assistant-glow/.pioenvs/home-assistant-glow/firmware.elf
collect2: fatal error: ld terminated with signal 9 [Killed]
compilation terminated.
*** [/data/home-assistant-glow/.pioenvs/home-assistant-glow/firmware.elf] Error 1
========================= [FAILED] Took 607.65 seconds =================== ======

Does anyone know what to do with it? I already had it working normally, but then I switched to another RPi and it doesn't work anymore. Thanks

**Comment by klaasnicolaas** [comment]
Unfortunately, I am not familiar with this error.
