### ISSUE TITLE
Photo diode help

### ISSUE THREAD

**Issue by itsboo07** [klaasnicolaas/home-assistant-glow#268]
Hi, this is a wonderful project but unfortunately I cant find the photodiode module in my location. rather can I buy this module (https://robu.in/product/lm393-photosensitive-light-dependent-control-sensor-module/) and replace the LDR with IR reciever like this (https://robu.in/product/5mm-940nm-infrared-receiver-led-ir-diode-led-pack-of-5/) and
will it work?
please help me back with your suggestions.

**Comment by klaasnicolaas** [comment]
This could possibly work quite well, expect the PCB to be identical.
