### ISSUE TITLE
How to calculate price as per the units consumed

### ISSUE THREAD

**Issue by itsboo07** [klaasnicolaas/home-assistant-glow#27]
Hi , this is great and thank you for wonderful project. as i saw in HA their is option to calculate static price per kWH consumed. but here in my place its completely different.  could anyone help me how to make this work in home assistant to calculate the cost as bellow. and here its calculated every two months
here the price is calculated per kwh with range
FOR
0-100kwh (no cost)
101-200kwh (3.5 rupees)
201-500kwh (4.6 rupees)
500kwh (6.6 rupees)

![calculation](https://user-images.githubusercontent.com/87331871/130049739-d51a0f9d-345b-45dc-b091-26f749033bd3.png)

**Comment by klaasnicolaas** [comment]
Do you use the Glow?

**Comment by lemppari** [comment]
This is not actually a glow issue and should be handled in home assistant. You might want to check this video https://youtu.be/UfLpVxS2QV4 I think it should give you a nice start for your problem.
