### ISSUE TITLE
Glow sending lots of data

### ISSUE THREAD

**Issue by floyd1111** [klaasnicolaas/home-assistant-glow#271]
Hi and thanks a lot for this great project! I was able to setup my HA Glow on a ESP32 with this photo diode (https://www.ebay.de/itm/274430239184) and integrated it in to home assistant. I sticked the sensor on my meter (ISKRA MT681) And now it's sending data. A lot of data. :)
On the webserver I can see an output of around 10 values per second for power consumption. The values are quite correct, no strange spikes.
Although I like detailed statistics. I am afraid to kill home assistant with this amount of data. 

Any advice to limit the output to maybe one value every 10 seconds?
Thanks very much for help!

**Comment by floyd1111** [comment]
I tried the changes from this pull request, and it seems to be working very well.
https://github.com/klaasnicolaas/home-assistant-glow/pull/269

**Comment by klaasnicolaas** [comment]
What pulse rate do you use?

**Comment by floyd1111** [comment]
I'm using a rate of 10000.
Right now the pulse meter seems to work very well. The total kwh seems ok too. But the total daily energy sensor stopped working. I added heartbeat: 60s in the filter section of the total daily energy sensor and now it is sending the same value on and on.

**Comment by floyd1111** [comment]
Alright, it seems the problem solved itself over night. After the reset of the daily sensor at midnight it's counting correctly. Don't have enough data yet to see how accurate the measurement is compared to the meter, but until now it looks primising. Thanks again for your help and this great little device!
