### ISSUE TITLE
No ability to update pulse via webserver

### ISSUE THREAD

**Issue by eyeisystems** [klaasnicolaas/home-assistant-glow#273]
New install of Glow, everything working fine but there's no option to update the pulse value on the webserver? 

![image](https://user-images.githubusercontent.com/15783882/217650391-1a503352-3fc3-48ef-a685-3a52297b37dc.png)

**Comment by klaasnicolaas** [comment]
Setting via the UI is part of version 4.0.0 and that is currently still in development. With the current version you are running now, you still have to adjust this in the yaml code.

**Comment by eyeisystems** [comment]
Ah no problem, it's just the current readme refers to this so thought i was going mad :)

**Comment by klaasnicolaas** [comment]
We have separate branches for what is stable and what is development, I'm still working on streamlining that better, but what you see by default is development.
