### ISSUE TITLE
Support for Xiao ESP32C3

### ISSUE THREAD

**Issue by BeardedTinker** [klaasnicolaas/home-assistant-glow#277]
Hi and let me star by saying AWESOME project.

Did play a bit with other boards with glow, but would love to try and make this work on micro board - Xiao ESP32C3.
Am I right thinking that D10 pin could be used instead of D7/D13
![image](https://user-images.githubusercontent.com/47822612/224542189-f7bab7d7-c4b1-49b5-beba-f56bf331a105.png)

This would make everything really compact. And it indicator is ditched, could almost fit in case for sensor board. (in terms of size).

Link to the board is here:
https://wiki.seeedstudio.com/XIAO_ESP32C3_Getting_Started/

**Comment by klaasnicolaas** [comment]
Expect you to be able to use that GPIO pin without any problems 😉
