### ISSUE TITLE
Does v4.0 work?

### ISSUE THREAD

**Issue by RamblingGeekUK** [klaasnicolaas/home-assistant-glow#279]
I ran version 3.x.x for a while, since launch and since upgrading to version 4, that data coming in is all over the place. Any  suggestions please?

**Comment by klaasnicolaas** [comment]
v4 is a development version that is still being worked on.

**Comment by RamblingGeekUK** [comment]
Thanks for the reply.  When I tried to go to version 3.x.x.  I just got version 4 again.   What did I miss?  Thanks again.

**Comment by klaasnicolaas** [comment]
There have been some adjustments with which version can be found on which branch and the current group of users have a slightly different yaml code, so that updating is based on the default branch in this repository (which is now  the `dev` branch).

**Comment by RamblingGeekUK** [comment]
Ah.. I missed that.  I think I understand.  Thank you for your prompt replies and for a great project.

**Comment by RamblingGeekUK** [comment]
I tried downloading the yaml from the main branch and the 3.1.1 branch and install and no matter what I do, I end up on version 4.0.0

<img width="580" alt="image" src="https://user-images.githubusercontent.com/7108949/225725963-50dc2f66-d9b6-4f4d-8806-3839e8d12f05.png">

**Comment by klaasnicolaas** [comment]
Change the package url to: `github://klaasnicolaas/home-assistant-glow/home_assistant_glow.yaml@main`

**Comment by RamblingGeekUK** [comment]
oh, doh! Thanks

**Comment by klaasnicolaas** [comment]
And there are more things that I actually want to release in the main branch from developtment, but I run into quite a few problems getting the CI/CD properly done with the release drafter and the way updates work in ESPHome. Any help for that is welcome.

**Comment by RamblingGeekUK** [comment]
Still no joy. https://www.youtube.com/watch?v=6rp4n62YjxA

**Comment by RamblingGeekUK** [comment]
> And there are more things that I actually want to release in the main branch from developtment, but I run into quite a few problems getting the CI/CD properly done with the release drafter and the way updates work in ESPHome. Any help for that is welcome.

I will have a poke around, I have very little knowledge of GitHub Actions and EPSHome but see if I can help.

**Comment by RamblingGeekUK** [comment]
Hmm, I guess there is no fix for it then... I will keep on poking, will post here if I find a solution.

**Comment by JiiTeeAm** [comment]
I've also installed version 4.0 and can't get i to work. Shows way too big numbers, even when the pulse setting is right. Is there a way to install previous version (manually)? Or some other help is welcome..

**Comment by klaasnicolaas** [comment]
You can only downgrade using the yaml file from the main branch

**Comment by RamblingGeekUK** [comment]
I have tried this so many times.. never works any more :-( So confused.

**Comment by klaasnicolaas** [comment]
Wouldn't really know, would have expected that adding `@main` would ensure that only the main branch is looked at 🤔 Could also just be a bug from ESPHome 🤷🏻‍♂️

**Comment by RamblingGeekUK** [comment]
I'm just trying again with a brand new ESP32 device, I have uninstalled EP32Home and reinstalled it.

**Comment by klaasnicolaas** [comment]
Will also grab an ESP32 and do some testing

**Comment by klaasnicolaas** [comment]
https://youtu.be/6rp4n62YjxA?t=80

Here I chose "Plug in to this computer" and after flashing I am running version 3.1.0

**Comment by vikohub** [comment]
> There have been some adjustments with which version can be found on which branch and the current group of users have a slightly different yaml code, so that updating is based on the default branch in this repository (which is now the `dev` branch).

Seems like having dev as the default branch leads to that if one downloads the yaml file manually from github (for initial install), one ends up downloading the 4.0.0 version. Is that on purpose?
I'm not quite sure I understood your comment above, but I'm guessing that has to do with how updating from ESPhome is supposed to work.

**Comment by klaasnicolaas** [comment]
It's the friction between how ESPHome handles updates when using `dashboard_import`, setting up a good git flow in this project for stables versions, doing development at the same time and making releases.

At some point, this branch split was chosen because otherwise people would already get breaking changes (such as a default pin switch), while this was something for v4.0 and not for the existing v3.x.

**Comment by RamblingGeekUK** [comment]
OK, I'm going to spend some time understanding  more about how ESPHome works with my own test project and see if I can get this figured out... no idea how long it will take

**Comment by vikohub** [comment]
Thx @klaasnicolaas .
Just to ensure I got this right and also chose the correct GPIO pin (may help others wondering):

-For those who want to use a stable version now, choose 'main' -> use 3.1.0 -> use pulse_pin: GPIO12

-For those looking to test, choose 'dev' -> use 4.0.0 -> use pulse_pin: GPIO13

Did I get that right?
