### ISSUE TITLE
erasing database

### ISSUE THREAD

**Issue by ozke86** [klaasnicolaas/home-assistant-glow#283]
Hi
how is it possible to delete the database
my House - Daily Energy is not at 126,124 kWh

![Unbenannt](https://user-images.githubusercontent.com/53629260/230714308-97df40c8-a643-42fe-acff-644695816500.PNG)

**Comment by klaasnicolaas** [comment]
After the night it will be reset anyway, at the moment we don't have a ready-made way to reset it at any time (a PR is open for it)
