### ISSUE TITLE
"hickup" values on steady light

### ISSUE THREAD

**Issue by jzielke84** [klaasnicolaas/home-assistant-glow#286]
Hi,

I've installed some solar energy panels which generate more power than I mostly use during normal operation (e.g. injecting the rest into the grid). That causes my Norax 3D mezer to show a steady pulse light (which equals 0 or "no power consumed"). HaGLow also ready this as as 0 but sometimes it causes some "hickups" in the data stream where short spikes are reported out of nowhere. It there any way to compensate this behaviour? Or a dup of https://github.com/klaasnicolaas/home-assistant-glow/issues/284 and https://github.com/klaasnicolaas/home-assistant-glow/issues/274 ?

![Screenshot 2023-04-30 at 10 58 07](https://user-images.githubusercontent.com/13448042/235344790-61e59f27-28b5-4961-8c0f-1e0f03960ffd.png)

**Comment by jzielke84** [comment]
Pussible dup of https://github.com/klaasnicolaas/home-assistant-glow/issues/284 ?

**Comment by jzielke84** [comment]
BTW: I hope I don't have to worry about the exclamation mark on the meter. According to the manual it means "negative results" (e.g. the solar energy being injected).

![IMG_3176](https://user-images.githubusercontent.com/13448042/235347008-93f774aa-e6cf-43ae-b413-184fca41be59.JPG)

**Comment by klaasnicolaas** [comment]
Maybe when you try the method option, mentioned [here](https://github.com/klaasnicolaas/home-assistant-glow/issues/274#issuecomment-1514097905)

**Comment by jzielke84** [comment]
Thanks @klaasnicolaas, however the graph shown above is showing the actual power consumption, not the total daily energy your comment is referring to.

**Comment by klaasnicolaas** [comment]
Actually, the glow is not really suitable for houses with solar panels, the pulse LED therefore behaves in a way that makes measuring difficult.

**Comment by jzielke84** [comment]
I’ve switched to the BitShake Smarter Reader so this issue is done.
