### ISSUE TITLE
ESP Resetting

### ISSUE THREAD

**Issue by SFreeman87** [klaasnicolaas/home-assistant-glow#289]
I finally managed to get this up and running, however It appears the ESP is resetting every minute or two..... any ideas? As it takes 30 seconds to boot back up again I'm missing a fair bit of log info!

Thank you.

14:46:42 | [D] | [sensor:110] | 'House - Daily Energy': Sending state 325.68814 kWh with 3 decimals of accuracy
-- | -- | -- | --
14:46:42 | [D] | [sensor:110] | 'House - Total Energy': Sending state 0.03000 kWh with 3 decimals of accuracy
14:46:42 | [D] | [light:035] | 'Red' Setting:
14:46:42 | [D] | [light:046] | State: OFF
14:47:16 | [D] | [sensor:110] | 'House - WiFi Signal': Sending state -90.00000 dBm with 0 decimals of accuracy
14:47:36 | [D] | [esp32.preferences:114] | Saving 1 preferences to flash...
14:47:36 | [D] | [esp32.preferences:143] | Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
14:47:48 | [I] | [ota:113] | Boot seems successful, resetting boot loop counter.
14:47:48 | [D] | [esp32.preferences:114] | Saving 1 preferences to flash...
14:47:48 | [D] | [esp32.preferences:143] | Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
14:47:50 | [D] | [sensor:110] | 'House - Power Consumption': Sending state 0.00000 W with 0 decimals of accuracy
14:47:50 | [D] | [light:035] | 'Red' Setting:

**Comment by SFreeman87** [comment]
Found a solution.

**Comment by klaasnicolaas** [comment]
Still issues?
