### ISSUE TITLE
Measurement on bi-directional meter (Germany/Zweirichtungszähler)

### ISSUE THREAD

**Issue by klaus1956** [klaasnicolaas/home-assistant-glow#29]
Hello
My house has a bi-directional meter with an IR-Signal (10.000 imp./kWh) which works fine with the sensor in general BUT:
As this is recording exported and imported energy the results fit to other measurements of imported or exported energy quite well, but as the impulses do not have an algebraic sign (math. +/-) the signal itself does not provide sensful measurements - especially when I try to interpret the total values over time.

![2021-08-24 08_22_25-](https://user-images.githubusercontent.com/79475518/130566546-13cae3d1-e6d4-4242-8a59-29a65502436c.jpg)

Does anybody have a good idea how to sepatate the imported and exported values?

![2021-08-24 08_04_30-Grafana - Home Assistant](https://user-images.githubusercontent.com/79475518/130566261-ae7f3240-14ba-452a-a58c-500bc42db7b3.jpg)
Green Line: Glow Sensor - Yellow Dots: Imported - Blue Dots: Exported

**Comment by yan14** [comment]
I don‘t think that this will work with this Interface. 
there is another Interface, which works with SML (https://www.msxfaq.de/sonst/bastelbude/smartmeter_d0_sml.htm).
But esphome has no library for sml, yet (https://github.com/esphome/feature-requests/issues/1041)

**Comment by klaus1956** [comment]
Thank you - Interesting.. I will follow this development

**Comment by ramdacxp** [comment]
The ESPHome SML component can be found here: https://esphome.io/components/sml.html.
In the picture above the SML send/receiver-diodes are hidden under the round sticker.
