### ISSUE TITLE
esp

### ISSUE THREAD

**Issue by cool-irr** [klaasnicolaas/home-assistant-glow#290]
hi
i have a programing esp8266-01.

c:/users/shedco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.1.0-gcc10.3-e5f9fec/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\SHEDco\AppData\Local\Temp\arduino\cores\e086725d524362f7173c3f551fb5b43a\core.a(core_esp8266_main.cpp.o): in function __loop_end': C:\Users\SHEDco\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.1.2\cores\esp8266/core_esp8266_main.cpp:245: undefined reference to setup'
c:/users/shedco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.1.0-gcc10.3-e5f9fec/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\SHEDco\AppData\Local\Temp\arduino\cores\e086725d524362f7173c3f551fb5b43a\core.a(core_esp8266_main.cpp.o):(.text._ZL12loop_wrapperv+0x25): undefined reference to `setup'
collect2.exe: error: ld returned 1 exit status

exit status 1

Compilation error: exit status 1

**Comment by klaasnicolaas** [comment]
I need more information than this 😉

**Comment by cool-irr** [comment]
> من به اطلاعات بیشتر از این نیاز دارم😉

What information do you neesd?

**Comment by klaasnicolaas** [comment]
Mainly more context, when did you get this, what have you already tried to solve it etc.

Unfortunately, I cannot help you with the above errors alone, because I have no idea where they come from and the relationship to the Home Assistant Glow.

**Comment by cool-irr** [comment]
> بیشتر زمینه، چه زمانی این را دریافت کردید، چه چیزی قبلاً برای حل آن تلاش کرده اید و غیره.
> 
> متأسفانه، من نمی‌توانم به تنهایی در مورد خطاهای فوق به شما کمک کنم، زیرا هیچ ایده‌ای ندارم که آنها از کجا می‌آیند و ارتباط آن با Home Assistant Glow چیست.

This program is related to Wi-Fi relay activation.  When I click on upload in Arduino, I get this error
