### ISSUE TITLE
Got values without connecting anything to the esp

### ISSUE THREAD

**Issue by vordenken** [klaasnicolaas/home-assistant-glow#295]
Like the title says I installed the esp32 with es-home and the glow setup and without even connecting any stuff to the esp (except power) it already posted values to HomeAssistant. Here's the screenshot:
<img width="487" alt="Bildschirmfoto 2023-06-21 um 11 17 07" src="https://github.com/klaasnicolaas/home-assistant-glow/assets/62395860/1689a9fe-5c09-432c-8cb7-13025afc9c9a">

**Comment by klaasnicolaas** [comment]
Can't really conclude from this what this could be, maybe you made contact with the pins so that it was registered as a pulse?

In any case, it resets itself back to 0 when the day is over and you could adjust the long term data in Home Assistant, or maybe reinstall the firmware.
