### ISSUE TITLE
Addresable LED support?

### ISSUE THREAD

**Issue by MariuszWoszczynski** [klaasnicolaas/home-assistant-glow#307]
Is it possible to modify the software so that instead of the standard RGB LED, the WS2812B can be used?

**Comment by klaasnicolaas** [comment]
It should be possible with some adjustments

**Comment by MariuszWoszczynski** [comment]
Have you an example? :)

**Comment by klaasnicolaas** [comment]
Maybe this: https://esphome.io/components/light/neopixelbus

It is really best to look at ESPHome for this and search what works, possibly go through the Home Assistant community forum 🤷🏻‍♂️
