### ISSUE TITLE
Pulse meter sensor took a long time

### ISSUE THREAD

**Issue by yarpsa** [klaasnicolaas/home-assistant-glow#310]
I have project_version: "4.0.0" and I keep getting
[component:204] | Component pulse_meter.sensor took a long time for an operation (0.05 s)
. Can you help me as a beginner, please?

**Comment by klaasnicolaas** [comment]
First of all, thank you for the donation.

The error does not immediately mean anything to me, have you looked in the issues of ESPHome to see if anyone has reported a similar problem?

**Comment by pikkmarg** [comment]
I had the same output but after updating to 2023.9.3 it has disappeared.
Reinstalling the Yaml might help.

**Comment by yarpsa** [comment]
Thanks.
Being investigated under esphome/issues#4717
