### ISSUE TITLE
House Total Energy get reset

### ISSUE THREAD

**Issue by peros550** [klaasnicolaas/home-assistant-glow#319]
Many thanks for your work. 
I have a small issue and thought I should report it. The House Total Energy sensor gets back to zero every few minutes. 

I can set it again to sync it with my home's meter but it resets by itself every few minutes. I am using an esp32 (nodemcu 30 pin) board with the following specification

  # Define the GPIO pins
  pulse_pin: GPIO23
  status_led: GPIO18
  led_pin_red: GPIO02
  led_pin_green: GPIO19

**Comment by klaasnicolaas** [comment]
Could it be that your ESP is constantly restarting or that it often loses the connection?

**Comment by peros550** [comment]
Thanks for the quick feedback. ESP's wifi signal seems strong, just a few meters from the AP and no walls but I don't know if it reboots itself. 

So if this to be expected when the connection to the HA is not rock solid or the esp looses power, that's ok.  On the other hand, the house daily energy seems to work nicely and does not get reset. Only the house total power gets reset.

**Comment by tomaszrondio** [comment]
have you found a solution? I get total energy reset every home assistant reboot. Turbo annoying

**Comment by klaasnicolaas** [comment]
It is a default behavior that the total entity always resets after reboot, there is a [PR open](https://github.com/klaasnicolaas/home-assistant-glow/pull/527) to make it a persistent value. Just haven't had the time to test it myself yet.

./Klaas

**Comment by tomaszrondio** [comment]
I think I solved it by using HA utility meter. Will see how convenient is that
