### ISSUE TITLE
Is anyone using an ESP8266?

### ISSUE THREAD

**Issue by bedfelllow** [klaasnicolaas/home-assistant-glow#37]
The project page makes reference to ESP32/8266. Does anyone have any experience using it with an ESP8266? I know they are both cheap cards, but I have spare ESP8266 cards which I try to use up for project that are suitable.

**Comment by KixMan28** [comment]
Yes, I have installed it on an Geekcreit ESP-12F module. It is still in test phase, but it seems to works. Please make sure that you change the platform and board to your specific setup.

**Comment by bedfelllow** [comment]
> Yes, I have installed it on an Geekcreit ESP-12F module. It is still in test phase, but it seems to works. Please make sure that you change the platform and board to your specific setup.

I think mine are ESP-12E so presumably I just need to change the platform and board to:

`  platform: ESP8266
  board: nodemcuv2`

**Comment by KixMan28** [comment]
Yes, this is what I use too.
