### ISSUE TITLE
ESP32-WROOM-32D_top_case.stl is a copy of ESP32-WROOM-32D_bottom_case.stl

### ISSUE THREAD

**Issue by chinswain** [klaasnicolaas/home-assistant-glow#373]
Just downloaded the ESP32 models, ESP32-WROOM-32D_top_case.stl appears to be a copy of ESP32-WROOM-32D_bottom_case.stl.

**Comment by klaasnicolaas** [comment]
@knaak Can you add the correct file? 😄 Thnx!

**Comment by knaak** [comment]
I will check.

**Comment by knaak** [comment]
That's embarrassing.  Fixed and PR submitted.
