### ISSUE TITLE
WebUi Username/Password?

### ISSUE THREAD

**Issue by RamblingGeekUK** [klaasnicolaas/home-assistant-glow#383]
What is the default username password ?

**Comment by klaasnicolaas** [comment]
Assuming you are using an older version, you can find that information here:

https://github.com/klaasnicolaas/home-assistant-glow/blob/v3.1.0/home_assistant_glow.yaml

**Comment by RamblingGeekUK** [comment]
Thanks found it now.  Is version 4.0 release now ?

**Comment by klaasnicolaas** [comment]
Version 4.0.0 was released a few weeks ago
