### ISSUE TITLE
Adoption problem

### ISSUE THREAD

**Issue by jiikoo** [klaasnicolaas/home-assistant-glow#401]
After successful installation, HomeAssistant suggests adoption, which succeeds. However, when I try to make changes to the Glow configuration file afterwards, the update fails and ends up in an error message "Home assistant glow ERROR Connecting to 192.168.xxx.xxx:3232 [Errno 111] Connection refused". I wondered about this for some time until I realized that the YAML file referred to a GitHub URL "klaasnicolaas.home-assistant-glow: github://klaasnicolaas/home-assistant-glow/home-assistant-glow/esp32.yaml@main", even though I am using an ESP8266 board. By fixing the URL to point to the correct yaml file "klaasnicolaas.home-assistant-glow: github://klaasnicolaas/home-assistant-glow/home-assistant-glow/esp32.yaml@main", the updates started to work.

**Comment by klaasnicolaas** [comment]
I see indeed that I forgot to change the `package_import_url` 😅
