### ISSUE TITLE
Add internal_filter to settings panel

### ISSUE THREAD

**Issue by bgmn** [klaasnicolaas/home-assistant-glow#431]
Could internal_filter be added to the settings panel just like the Puls rate - imp/kW is now added? That way you could change the internal filter value and still get the updates from github.

**Comment by klaasnicolaas** [comment]
Currently the easiest way to use the `internal_filter` is to use an extend as described in the recently updated documentation. Maybe we can bring the option to the UI via a text component, but I have to investigate that further first.

./Klaas

**Comment by bgmn** [comment]
Thank you! Good old rtfm worked again. :)
