### ISSUE TITLE
KWh meter whit Wemos D1 mini?

### ISSUE THREAD

**Issue by tiimsvk** [klaasnicolaas/home-assistant-glow#44]
is it possible to use [ESP Wemos D1 mini](https://www.aliexpress.com/item/1005002512406896.html?spm=a2g0s.9042311.0.0.27424c4dD22O81)?
If so, can you advise what needs to be adjusted to make it work?
well thank you

**Comment by klaasnicolaas** [comment]
Change the `platform` and `board`, same as we advised here: https://github.com/klaasnicolaas/home-assistant-glow/issues/37

**Comment by tiimsvk** [comment]
Well thank you.
My question: Where to connect DO on Photodiode?

**Comment by klaasnicolaas** [comment]
If I see that schematic, it should indeed be D6.

**Comment by RubenKelevra** [comment]
Can we extend the recommended hardware to include the Wemos D1 mini, as it's much more affordable to use them (and we really don't need any ESP32 feature - right?)

**Comment by m-s-e** [comment]
> Can we extend the recommended hardware to include the Wemos D1 mini, as it's much more affordable to use them (and we really don't need any ESP32 feature - right?)

i think so - my D1mini has been running for a few weeks now without problems

**Comment by klaasnicolaas** [comment]
We've already added the Wemos to the diagram, I think that's enough.
