### ISSUE TITLE
Resistor for output LED?

### ISSUE THREAD

**Issue by lemppari** [klaasnicolaas/home-assistant-glow#49]
Has anybody used a resistor for the output LED using the components mentioned in the readme file? If I understand correctly ESP32 pins supply 3.3V and the output LED is rated for 3V.

**Comment by klaasnicolaas** [comment]
Actually it should have a resistor on every data pin of an RGB LED, but personally I have omitted that and after months it still works.

**Comment by lemppari** [comment]
Maybe adding a 100 ohm resistor to cathode (common for all) could be on the safe side.

**Comment by lemppari** [comment]
Actually this maybe should have gone to discussion. Anyway I used an 100 ohm resistor in cathode and it works just fine. Whole setup seems to be ok. Big thanks for this project!! :)
