### ISSUE TITLE
last_reset_type error with latest ESPHome Update 2021.9.0

### ISSUE THREAD

**Issue by pschneider87** [klaasnicolaas/home-assistant-glow#51]
With the new 2021.9.0 Update of ESP Home, I get the following warning in the code

![image](https://user-images.githubusercontent.com/17707309/133560667-273882cc-b570-4ea1-be6a-bb53f6c84a4c.png)

**Comment by Eddie46848** [comment]
Seeing the same also and I'm already on version 2 yaml.
It says measurement type is wrong.

**Comment by Eddie46848** [comment]
> Seeing the same also and I'm already on version 2 yaml.
> It says measurement type is wrong.

Sorry just seen the proposed changes, will wait for newer version.

Thanks

**Comment by klaasnicolaas** [comment]
You're just ahead of me with an update 😄
