### ISSUE TITLE
Updates.yaml

### ISSUE THREAD

**Issue by ItsMeRitch** [klaasnicolaas/home-assistant-glow#515]
The updates.yaml file does not exist in the latest 4.0.2 version. 

<img width="636" alt="Screenshot 2024-07-02 at 15 28 17" src="https://github.com/klaasnicolaas/home-assistant-glow/assets/55960162/ba0d30e9-9302-4058-b0e3-15365fd4ea0a">

<img width="2027" alt="Screenshot 2024-07-02 at 15 28 51" src="https://github.com/klaasnicolaas/home-assistant-glow/assets/55960162/4c050305-17d1-44a3-8da3-564f883059db">

**Comment by klaasnicolaas** [comment]
Tomorrow there will be a new release that fixes this.

./Klaas

**Comment by ItsMeRitch** [comment]
> Tomorrow there will be a new release that fixes this.
> 
> ./Klaas

Fantastic, thank you
