### ISSUE TITLE
Package problem

### ISSUE THREAD

**Issue by bimbopp** [klaasnicolaas/home-assistant-glow#526]
Hello. I am getting an error during validation.
`Failed to load packages. components/basis.yaml does not exist in repository.
  remote_package: 
    url: https://github.com/klaasnicolaas/home-assistant-glow/
    ref: 4.1.0
    files: 
      - components/basis.yaml
      - components/updates.yaml
      - components/status_led.yaml
      - components/pulse_meter.yaml`

**Comment by klaasnicolaas** [comment]
When do you get this? I cannot reproduce it.

./Klaas

**Comment by bimbopp** [comment]
Sorry for the rookie mistake. Clean Build Files and the problem is gone.
