### ISSUE TITLE
release 4.1.0 - Nodemcu systems cannot connect  

### ISSUE THREAD

**Issue by peter656761** [klaasnicolaas/home-assistant-glow#528]
I am a relatively new user of Homeassistant and Nodemcu boards but have  found the latest release 4.1.0 seems to have stopped working 

For example I can flash via cable a new NodeMCU esp8266.  It asks for wifi credentials that are input and it gets an ip address.
Going to add the unit to ESP home I notice that the included link is for the D1 mini not the esp.  I can leave it as a D1 or change it to the esp and either way then adopt the board and install.  This is the only time the logs are visible and I see that it connects to the homeassitant and then disconnects continually.

Upgrading produces the same result - a system seemingly installed but cannot be connected to

 
![20240706_121806813_iOS](https://github.com/klaasnicolaas/home-assistant-glow/assets/116889540/de5ca229-a4cb-46d9-864d-bdfae829b387)

**Comment by klaasnicolaas** [comment]
Which board exactly do you have?

./Klaas

**Comment by klaasnicolaas** [comment]
After testing, I have also noticed that the D1 Mini firmware is being used, so I'm going to look for a solution for that. I wouldn't know of an immediate solution other than removing the device everywhere and trying to add it again.

./Klaas

**Comment by klaasnicolaas** [comment]
Have you been able to find a solution yourself in the meantime?

./Klaas

**Comment by peter656761** [comment]
Hi Klaas

Thank you for the email.  I had to manually initiate the Nodemcu install via ESPhome then adopt it into Homeassistant.

I then downloaded your  yaml and made a few modifications to work perfectly thank you

Regards
Peter#
