### ISSUE TITLE
How to send data without wifi?

### ISSUE THREAD

**Issue by phil-schneider** [klaasnicolaas/home-assistant-glow#56]
Hello,
how can I send the data if I have no WiFi access at the locaion of the meter?

Thanks

**Comment by klaus1956** [comment]
Not so many possibilities - how about either a wired WIFi-accesspoint or something using Powerline?

**Comment by mrand** [comment]
> Hello, how can I send the data if I have no WiFi access at the locaion of the meter?

I'd expect you'd be able to use one of the ESP32 modules that have Ethernet.  Here are the ones currently supported by ESPhome:

https://esphome.io/components/ethernet.html

**Comment by phil-schneider** [comment]
Thanks a lot.
I think I have to use an external wifi Antenna and an extender.
Lan is a an Option I did not know about for esp, but not in my case.
