### ISSUE TITLE
Is it normal for the bright green LEDs on the photodiode to be on?

### ISSUE THREAD

**Issue by tejasitraj** [klaasnicolaas/home-assistant-glow#58]
Is it normal for the pwr-led on the photodiode to be always on? I feel like my energy meter's LED has no chance against that bright green LED...

And when i increase the sensitivity of the diode, the DO-LED comes on as well..
![20210919_155416 (1)](https://user-images.githubusercontent.com/14822776/133930242-cecab204-5ae0-41f9-947e-02e79e716f66.jpg)
.

**Comment by moorep999** [comment]
Mine does the same. Power always on, and the other when the photodiode detects light. The 3d printed enclosure for the diode has a partition between the LEDs and the diode to help stop stray light. Compared to my meter’s LED, they’re much brighter.

Can you use some duct tape/cardboard to isolate the diode and give it a better chance of detecting?

**Comment by jurgenweber** [comment]
was going to ask the same question, since the LED flash from my meter is so soft I was concerned about this.. but I also think both my lights are on all the time. Sounds like this is incorrect.

**Comment by RubenKelevra** [comment]
> Mine does the same. Power always on, and the other when the photodiode detects light. The 3d printed enclosure for the diode has a partition between the LEDs and the diode to help stop stray light. Compared to my meter’s LED, they’re much brighter.
> 
> Can you use some duct tape/cardboard to isolate the diode and give it a better chance of detecting?

So your module looks the same and is working fine? I have trouble getting mine to recognize the light from my meter, while I cranked the sensitivity up to the maximum where the DO-LED stays off when it's in total darkness.

**Comment by RubenKelevra** [comment]
> was going to ask the same question, since the LED flash from my meter is so soft I was concerned about this.. but I also think both my lights are on all the time. Sounds like this is incorrect.

I think DO-LED means that the module sends a digital 1 out, so "light is there". So it should be off as long as there's no flash from the meter - as far as I understand.

**Comment by moorep999** [comment]
> > Mine does the same. Power always on, and the other when the photodiode detects light. The 3d printed enclosure for the diode has a partition between the LEDs and the diode to help stop stray light. Compared to my meter’s LED, they’re much brighter.
> > Can you use some duct tape/cardboard to isolate the diode and give it a better chance of detecting?
> 
> So your module looks the same and is working fine? I have trouble getting mine to recognize the light from my meter, while I cranked the sensitivity up to the maximum where the DO-LED stays off when it's in total darkness.

Turns out my photodiode was installed backwards. Came across a random comment a while ago. They’ve now referenced it in the main glow page (issue 34)
https://github.com/klaasnicolaas/home-assistant-glow

**Comment by RubenKelevra** [comment]
Hm I've checked that. Let me double check that :)

**Comment by klaasnicolaas** [comment]
I think the main question has already been answered. Yes, this LED is always on and the case tries to block the light as much as possible so that it does not affect the sensor. Can we close the issue?

**Comment by tejasitraj** [comment]
Absolutely, thank you!
