### ISSUE TITLE
Calculation of per minute energy usage

### ISSUE THREAD

**Issue by stevel23** [klaasnicolaas/home-assistant-glow#59]
Apologies if I have got this wrong but isn't line 111 of the yaml file incorrect if your pulse rate is not 1000. If for example the pulse rate is 4000 then the current calculation      " - lambda: return x * ((60.0 / ${pulse_rate}) * 1000.0);"  ends up giving an estimate of 15 minutes consumption not per hour. i would suggest that it needs to be multiplied by pulse rate not 1000 -

Apologies I have just realised my error - please ignore

**Comment by klaasnicolaas** [comment]
The multiply of 1000 is to convert kW -> W 😉
