### ISSUE TITLE
Usage double actual use

### ISSUE THREAD

**Issue by Dale-Muccignat** [klaasnicolaas/home-assistant-glow#592]
Hiya, love your work on this and appreciate your efforts. This is more of an FYI unless there's some clarity others had.

I was setting up my own glow and having trouble adjusting the sensitivity on the photodiode. It seemed unless I got it perfect it would either not register pulses or double count them. My meter is outside in a not very sealed box so perhaps that doesn't help.

I just added the following options to my config:
```
internal_filter: 200ms
internal_filter_mode: PULSE
```
I have had the 200ms filter in for a while but adding the filter mode seems to have solved the doublt counting issue. 

I'm not entirely across why, I think it might be something to do with the daylight but I don't really understand why it would be.

**Comment by osro** [comment]
I have exactly same issue. All the values are doubled to what the actual usage is. I have checked all the settings should be ok.

**Comment by LSgeo** [comment]
Same here. I remember fixing it on my last installation but accidentally removed it the device from HA / esphome and will have to re-figure it out.

**Comment by LSgeo** [comment]
Found my old config - Add a PULSE filter with appropriate size (mine was 200ms) as a sensor !extend to the ha-glow.yaml config:
```
sensor:
  - id: !extend sensor_energy_pulse_meter
    internal_filter: 200ms
    internal_filter_mode: PULSE
```

See before/after of my consumption history (edited about 9:45 pm):

<img width="1920" height="678" alt="Image" src="https://github.com/user-attachments/assets/5462228c-98f1-411c-a07b-961b6012a012" />

p.s I have rotated the api key :fire:
