### ISSUE TITLE
24hr reset

### ISSUE THREAD

**Issue by glendower** [klaasnicolaas/home-assistant-glow#66]
How do I reset the energy reading to zero at midnight, and also is it normal for power reading to be zero occasionally.

Thanks for the yaml code, I tried to code it myself and I got very close to your solution, its the lambda bits I don't understand, more reading required I think

**Comment by nefelodamon** [comment]
Hi,

You should not have to reset anything. What you need to do is to implement an utility meter in HomeAssistant that will track the usage.

The Utility Meter will count the energy used (the pulses of your meter) and you can have the energy meter automatically reset every day, week, month, year etc.
See info here: https://www.home-assistant.io/integrations/utility_meter/

Not sure about the power reading be zero. I think documentation says that if no pulse is detected for 5 minutes (default unconfigured value) it will then show zero?

**Comment by glendower** [comment]
Thanks for that, I am already using the utility meter for my consumption and export, I just didn't think to use it with this.
As regards the zero reading this was solved by reintroducing 100ms filter that was commented out.
