### ISSUE TITLE
Documentation clarification

### ISSUE THREAD

**Issue by wormiedk** [klaasnicolaas/home-assistant-glow#67]
I had HUGE problems with flashing my board until I removed all dupont wires before flashing... I think the order of your tutorial might be problematic. Further it would be great if you added a small section on the different methods to flash esphome as not all users are running home assistant supervised :)

**Comment by nathanhaigh** [comment]
I have just received all the parts for this project from banggood. This is my first ever ESP32 project and I will likely have some recommendations for the documentation. I'll send PRs in due course.

**Comment by DrJon85** [comment]
> I have just received all the parts for this project from banggood. This is my first ever ESP32 project and I will likely have some recommendations for the documentation. I'll send PRs in due course.

likewise, this is my first and i am struggling to work it out.

**Comment by nathanhaigh** [comment]
> likewise, this is my first and i am struggling to work it out.

What were you struggling with @DrJon85? Maybe I could help out.

**Comment by Helmasynti** [comment]
I do not know whether this is the right issue to put this comment but I hope this helps somebody in trouble:
1) Current version of Glow uses GPIO13 for the photodiode whereas the former ones used GPIO12. If you just updated the firmware but did not resolder the wire from GPIO12 to GPIO13, your Glow stops reading flashes. I think that there should be more explicit warning about this than there is now and also clear instructions how the situation can be solved either by resoldering or by editing the yaml file. 
2) If you choose to edit the yaml file, it is done by downloading home_assistant_glow.yaml to your config/esphome and then editing it directly by an editor or via ESPHome addon.
3) If you forget to edit your Wifi network's SSID and password AND also uncomment them (!), you can no longer reach Glow wirelessly but you have to connect it via USB. This may be tricky. I know that this is more like an ESP32 related problem but there could be something about this in the documentation. In case you cannot connect your ESP32 with USB, I want you to know this: some USB wires work and some don't. I was just forced to flash my ESP32 with USB and I had to try three different USB wires before I managed to establish a connection! If it happened to me, it can happen to you as well.
4) Thank you klaasnicolaas for a magnificient work!

**Comment by klaasnicolaas** [comment]
@Helmasynti I think it would be better to raise a discussion or issue, depending on the point in your list.

Closing this issue now, because the original issue has been solved.
