### ISSUE TITLE
Documenation: which Model for case? 

### ISSUE THREAD

**Issue by phil-schneider** [klaasnicolaas/home-assistant-glow#76]
Hello,
Could you please document which esp Model fits perfect into the case.
I have printed the case and tried three different esp models. None really fit.
There are so many different models on AliExpress.
Could you please say for which the case was made?
And please also document this 🙂.

Thanks a lot

**Comment by klaasnicolaas** [comment]
The case is made for the Geekcreit ESP32, under the shopping list is a link to Banggood.
