### ISSUE TITLE
Inverted LED in meter

### ISSUE THREAD

**Issue by exxico** [klaasnicolaas/home-assistant-glow#84]
Hello.
The LED on my meter is constantly on, and only goes out for a moment when it is triggered. In the ESP logs - a stream of data, debug messages about triggering are poured chaotically. As a result, consumption is cosmic. Meter is Merkuriy 201 - russian made.
...
In the sensor, the 2 on-chip comparator is not involved and could be used to invert the signal. or change the behavior of the first one by giving an inverted signal to the comparison input, but this is a theory and I will think of it.

**Comment by exxico** [comment]
Sorry, false alarm. The problem is pure esp-12e with harness. Put on wemos-mini and everything took off. internal_filter: 50ms

**Comment by exxico** [comment]
worked as it should. only a very very fine adjustment of the resistor is required at the very beginning of the sensitivity.

**Comment by klaasnicolaas** [comment]
In that case could we close the issue?
