### ISSUE TITLE
Drop to 0 watt

### ISSUE THREAD

**Issue by JJ00-dk** [klaasnicolaas/home-assistant-glow#85]
Hi - I get a lot of drops down to 0 watt and then it return back to the actually (live) power consumtiion. Any idea why this happens? And maybe how to fix it?

Thanks in advance

**Comment by Eddie46848** [comment]
I usually find this is when the WiFi connection drops out.

**Comment by JJ00-dk** [comment]
Seems like the "internal_filter: 100ms" did the trick so far.

**Comment by RubenKelevra** [comment]
Not sure about the timeframe for this "drops", but after 300 Seconds it is expected to drop down to 0.

`[23:00:22][C][pulse_meter:056]:   Assuming 0 pulses/min after not receiving a pulse for 300s`

**Comment by JJ00-dk** [comment]
The internal filter worked for me - no drops to 0 and no spiks to 100.000 watt anymore
