### ISSUE TITLE
Entity category diagnostic not reflected

### ISSUE THREAD

**Issue by frimtec** [klaasnicolaas/home-assistant-glow#88]
Just updated to release home-assistant-glow v2.2.0 using HA 2021.11.4 and ESPHome 2021.11.1.

Now the text sensors for SSID, version and IP address should be categorized as diagnostic sensors, but they are not:
![glow-2 2 0](https://user-images.githubusercontent.com/3511114/142586159-44233ec4-5884-4e44-995f-6db914bcce8c.PNG)

From another project where I do not use the extra tags "entity_category: diagnostic" I realized that the same text sensors as the ones used in home-assistant-glow are automatically categorized as diagnostic sensors.

Now I removed the  extra tags "entity_category: diagnostic" also in home-assistant-glow and voila, it is correctly shown in HA now:
![glow-2 2 0-fix](https://user-images.githubusercontent.com/3511114/142586671-2541d622-13d4-409f-bb52-92481e1f4041.PNG)

**Comment by klaasnicolaas** [comment]
It is probably more of a caching or reloading problem because it should overrule the default values. That said, I'm still going to approve your PR, as there's no need to add the `entity_category`.
