### ISSUE TITLE
[Question] Link to AliExpress for LED RGB 5mm 4 pin - cathode

### ISSUE THREAD

**Issue by VivantSenior** [klaasnicolaas/home-assistant-glow#96]
Hi,

I've noticed that there is no aliexpress link to buy LED RGB 5mm 4 pin (cathode). Is [this item](https://www.aliexpress.com/item/4000225253691.html) suitable? (cathode-transparent option)

Best,
Viv

**Comment by klaasnicolaas** [comment]
Think these are fine, will add them to the list too 😉
