### ISSUE TITLE
Total energy usage for today only

### ISSUE THREAD

**Issue by Beenay25** [klaasnicolaas/home-assistant-glow#97]
I may be missing something obvious, but is it possible to get the energy used today only?

I can get the current energy usage, and the total energy usage. But the total seems to be for all time (I'm currently showing 8kwh total where my actual usave is about 2.5kwh for today.

Is there a way to get it to reset this total value at midnight?

**Comment by Beenay25** [comment]
Hi,

Thanks for adding the new-feature flag.

If you're adding this as something new, it might be handy to be able to state when the count resets. Like midnight, or 4am etc...

**Comment by klaasnicolaas** [comment]
I never added the day entity because the total kWh entity for the energy dashboard is enough, but can still add it eventually. The reset happens by default at midnight, I don't know if we can change that much 🤔

**Comment by Beenay25** [comment]
Is there a way for us to manually reset the value? An API call or something?

It's an excellent product. So easy to get running :)

**Comment by klaasnicolaas** [comment]
Maybe we can make an extra reset service for the day entity 😄

**Comment by klaasnicolaas** [comment]
I'm trying some things out with the new options in 2021.12 
![image](https://user-images.githubusercontent.com/20448157/146201701-8007b5f4-9d97-4d1a-9bbc-c6f06a55c762.png)
